=== KamarasE/EN4B5KWebXML/EN4B5K_XMLTask/EN4B5K_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

        <!--Elemek ref-hez-->
    <xs:element name="név" type="xs:string" />
    <xs:element name="elérhetőség" type="elérhetőségTípus" />

    <!-- Saját egyszerű típusok meghatározása, megszorítás -->
    <xs:simpleType name="nemTípus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M" />
            <xs:enumeration value="F" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="jogviszonyTípus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="állami" />
            <xs:enumeration value="fizetős" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="aktívTípus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen" />
            <xs:enumeration value="nem" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="időTípus">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minExclusive value="8" />
            <xs:maxExclusive value="15" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="emailTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]([a-z0-9_.-]*)@[a-z]([a-z0-9_-]*).[a-z]{2,4}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="telefonTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([+]?)\d{11}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="elégedettségTípus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--Komplex típusokhoz saját típus meghatározása, sorrendiség, számosság etc. -->
    <xs:complexType name="elérhetőségTípus">
        <xs:sequence>
            <xs:element name="telefonszám" type="telefonTípus" />
            <xs:element name="email" type="emailTípus" minOccurs="1" maxOccurs="5" />    
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="időpontTípus">
        <xs:sequence>
            <xs:element name="dátum" type="xs:date" />
            <xs:element name="kezdete" type="időTípus" />
            <xs:element name="vége" type="időTípus" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="betegTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element name="lakcím" type="xs:string" />
            <xs:element name="születési_dátum" type="xs:date" />
            <xs:element name="neme" type="nemTípus" />
        </xs:sequence>
        <xs:attribute name="Bid" type="xs:integer" use="required" />
        <xs:attribute name="hozzátartozó" type="xs:integer" use="required" />
        <xs:attribute name="ellátás" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="ellátásTípus">
        <xs:all>
            <xs:element name="típus" type="xs:string" />
            <xs:element name="időtartam" type="xs:date" />
            <xs:element name="jogviszony" type="jogviszonyTípus" />
        </xs:all>
        <xs:attribute name="Eid" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="hozzátartozóTípus">
        <xs:sequence>
            <xs:element ref="név" />        
            <xs:element name="kapcsolat" type="xs:string" />
            <xs:element ref="elérhetőség" />
        </xs:sequence>
        <xs:attribute name="Hid" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="szakrendelésTípus">
        <xs:sequence>
            <xs:element name="panasz" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="diagnózis" type="xs:string" />
            <xs:element name="időpont" type="időpontTípus" />
        </xs:sequence>
        <xs:attribute name="Szid" type="xs:integer" use="required" />
        <xs:attribute name="Oid" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="részvételTípus">
        <xs:sequence>
            <xs:element name="elégedettség" type="elégedettségTípus"  />
            <xs:element name="terápia" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="szakrendelés" type="xs:integer" use="required" />
        <xs:attribute name="beteg" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="orvosTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element name="szakterület" type="xs:string" minOccurs="0" maxOccurs="1" />        
            <xs:element name="fizetés" type="xs:positiveInteger" />
            <xs:element ref="elérhetőség"/>
        </xs:sequence>
        <xs:attribute name="Oid" type="xs:integer" use="required" />
    </xs:complexType>

    <!-- Gyökérelemtől az elemek felhasználása -->
    <xs:element name="kórház">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="beteg" type="betegTípus" minOccurs="0" maxOccurs="100" />
                <xs:element name="ellátás" type="ellátásTípus" minOccurs="0" maxOccurs="100" />
                <xs:element name="hozzátartozó" type="hozzátartozóTípus" minOccurs="0" maxOccurs="100" />
                <xs:element name="szakrendelés" type="szakrendelésTípus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="részvétel" type="részvételTípus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="orvos" type="orvosTípus" minOccurs="1" maxOccurs="100" />
            </xs:sequence>
        </xs:complexType>

        <!-- Elsődleges kulcsok -->
        <xs:key name="beteg_kulcs">
            <xs:selector xpath="beteg" />
            <xs:field xpath="@Bid" />
        </xs:key>
        <xs:key name="ellátás_kulcs">
            <xs:selector xpath="ellátás" />
            <xs:field xpath="@Eid" />
        </xs:key>
        <xs:key name="hozzátartozó_kulcs">
            <xs:selector xpath="hozzátartozó" />
            <xs:field xpath="@Hid" />
        </xs:key>
        <xs:key name="szakrendelés_kulcs">
            <xs:selector xpath="szakrendelés" />
            <xs:field xpath="@Szid" />
        </xs:key>
        <xs:key name="orvos_kulcs">
            <xs:selector xpath="orvos" />
            <xs:field xpath="@Oid" />
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref name="beteg_ellátás_kulcs" refer="ellátás_kulcs">
            <xs:selector xpath="beteg" />
            <xs:field xpath="@ellátás" />
        </xs:keyref>
        <xs:keyref name="beteg_hozzátartozó_kulcs" refer="hozzátartozó_kulcs">
            <xs:selector xpath="beteg" />
            <xs:field xpath="@hozzátartozó" />
        </xs:keyref>
        <xs:keyref name="szakrendelés_orvos_kulcs" refer="orvos_kulcs">
            <xs:selector xpath="szakrendelés" />
            <xs:field xpath="@orvos" />
        </xs:keyref>
        <xs:keyref name="részvétel_beteg_kulcs" refer="beteg_kulcs">
            <xs:selector xpath="részvétel" />
            <xs:field xpath="@beteg" />
        </xs:keyref>
        <xs:keyref name="részvétel_szakrendelés_kulcs" refer="szakrendelés_kulcs">
            <xs:selector xpath="részvétel" />
            <xs:field xpath="@szakrendelés" />
        </xs:keyref>

        <!-- Az 1:1 kapcsolat megvalósítása -->
        <xs:unique name="beteg_ellátás_1_1">
            <xs:selector xpath="beteg" />
            <xs:field xpath="@ellátás" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== KamarasE/EN4B5KWebXML/EN4B5K_XMLTask/EN4B5K_XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<kórház xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
 xs:noNamespaceSchemaLocation="EN4B5K_XMLSchema.xsd">

<!--Betegek-->


<beteg Bid="10" hozzátartozó="100" ellátás="1000">
    <név>Kiss Ernő</név>
    <lakcím>Görömböly</lakcím>
    <születési_dátum>1982-11-11</születési_dátum>
    <neme>M</neme>
</beteg>
<beteg Bid="11" hozzátartozó="110" ellátás="1001">
    <név>Nagy Anna</név>
    <lakcím>Bükkaranyos</lakcím>
    <születési_dátum>1976-11-08</születési_dátum>
    <neme>F</neme>
</beteg>
<beteg Bid="12" hozzátartozó="120" ellátás="1002">
    <név>Szép Roland</név>
    <lakcím>Miskolc</lakcím>
    <születési_dátum>1998-02-04</születési_dátum>
    <neme>M</neme>
</beteg>
<beteg Bid="13" hozzátartozó="120" ellátás="1003">
    <név>Szép Anita</név>
    <lakcím>Mályi</lakcím>
    <születési_dátum>1999-01-06</születési_dátum>
    <neme>F</neme>
</beteg>

<!--ellátás adatok-->
<ellátás Eid="1000">
    <időtartam>2016-09-01</időtartam>
    <típus>sürgős</típus>
    <jogviszony>fizetős</jogviszony>
</ellátás>
<ellátás Eid="1001">
    <időtartam>2015-09-01</időtartam>
    <típus>nem sürgős</típus>
    <jogviszony>állami</jogviszony>
</ellátás>
<ellátás Eid="1002">
    <időtartam>2013-09-01</időtartam>
    <típus>nem sűrgős</típus>
    <jogviszony>állami</jogviszony>
</ellátás>
<ellátás Eid="1003">
    <időtartam>2013-09-01</időtartam>
    <típus>sügrős</típus>
    <jogviszony>állami</jogviszony>
</ellátás>

<!--hozzátartozók-->
<hozzátartozó Hid="100">
    <név>Kiss Ádám</név>
    <kapcsolat>Szülő</kapcsolat>
    <elérhetőség>
        <telefonszám>+36306060769</telefonszám>
        <email>adamkiss@gmail.com</email>
        <email>kissadam@citromail.hu</email>
    </elérhetőség>
</hozzátartozó>
<hozzátartozó Hid="110">
    <név>Nagy Éva</név>
    <kapcsolat>Gyermek</kapcsolat>
    <elérhetőség>
        <telefonszám>+36201234987</telefonszám>
        <email>n.eva.dies@gmail.com</email>
    </elérhetőség>
</hozzátartozó>
<hozzátartozó Hid="120">
    <név>Komly János</név>
    <kapcsolat>Szülő</kapcsolat>
    <elérhetőség>
        <telefonszám>+36706969696</telefonszám>
        <email>komjancsi@kommail.hu</email>
        <email>jancsi.komoly@gmail.com</email>
        <email>jancsika@freemail.com</email>
    </elérhetőség>
</hozzátartozó>
<!--Szakrendelések-->
<szakrendelés Szid="1200" Oid="1100">
    <panasz>láz</panasz>
    <diagnózis>Felső légúti fertőzés</diagnózis>
    <időpont>
        <dátum>2025-10-30</dátum>
        <kezdete>12</kezdete>
        <vége>13</vége>
    </időpont>
</szakrendelés>
<szakrendelés Szid="1201" Oid="1100">
    <panasz>fájdalom</panasz>
    <diagnózis>Vírusfertőzés</diagnózis>
    <időpont>
        <dátum>2025-10-15</dátum>
        <kezdete>9</kezdete>
        <vége>10</vége>
    </időpont>
</szakrendelés>
<szakrendelés Szid="1202" Oid="1101">
    <panasz>hasi fájdalom</panasz>
    <panasz>fájdalmas vizelés</panasz>
    <diagnózis>hólyaggyulladás</diagnózis>
    <időpont>
        <dátum>2025-09-02</dátum>
        <kezdete>12</kezdete>
        <vége>13</vége>
    </időpont>
</szakrendelés>
<szakrendelés Szid="1203" Oid="1102">
    <panasz>torok fájdalom</panasz>
    <diagnózis>mandulagyulladás</diagnózis>
    <időpont>
        <dátum>2025-11-25</dátum>
        <kezdete>11</kezdete>
        <vége>12</vége>
    </időpont>
</szakrendelés>

<!--Részvételi adatok-->
<részvétel beteg="10" szakrendelés="1200">
    <elégedettség>5</elégedettség>
    <terápia>antihisztamin</terápia>
</részvétel>
<részvétel beteg="10" szakrendelés="1201">
    <elégedettség>4</elégedettség>
    <terápia>antibiotikum</terápia>
</részvétel>
<részvétel beteg="11" szakrendelés="1201">
    <elégedettség>5</elégedettség>
    <terápia>NSAID</terápia>
</részvétel>
<részvétel beteg="12" szakrendelés="1200">
    <elégedettség>2</elégedettség>
</részvétel>
<részvétel beteg="12" szakrendelés="1202">
    <elégedettség>3</elégedettség>
</részvétel>
<részvétel beteg="13" szakrendelés="1203">
    <elégedettség>5</elégedettség>
    <terápia>fájdalomcsillapító</terápia>
</részvétel>

<!--orvosok-->
<orvos Oid="1100">
    <név>Takács Imre</név>
    <szakterület>Sebész</szakterület>
    <fizetés>500000</fizetés>
    <elérhetőség>
        <telefonszám>+36702525252</telefonszám>
        <email>t.i@gmail.com</email>
    </elérhetőség>
</orvos>
<orvos Oid="1101">
    <név>Kovács Kálmán</név>
    <szakterület>Belgyógyász</szakterület>
    <fizetés>250000</fizetés>
    <elérhetőség>
        <telefonszám>+36303636363</telefonszám>
        <email>kovka@gmail.com</email>
        <email>kovacs.k@freemail.hu</email>
    </elérhetőség>
</orvos>
<orvos Oid="1102">
    <név>Szűz Emilia</név>
    <szakterület>Füll-Orr-gégész</szakterület>
    <fizetés>950000</fizetés>
    <elérhetőség>
        <telefonszám>+36705555555</telefonszám>
        <email>szuzemi@gmail.com</email>
    </elérhetőség>
</orvos>


 </kórház>
